bags_list = [
['dim silver', 'contain', '3 posh fuchsia'],
['wavy olive', 'contain', '1 striped olive', '1 dull cyan'],
['dull coral', 'contain', '1 dim olive', '5 muted violet', '2 dark gray'],
['bright olive', 'contain', '3 light indigo', '3 dark coral'],
['clear lavender', 'contain', '1 dark olive'],
['dim lime', 'contain', '3 dotted red'],
['drab indigo', 'contain', '5 striped coral', '2 muted bronze'],
['striped orange', 'contain', '5 wavy fuchsia', '5 clear red', '3 plaid red'],
['dotted indigo', 'contain', '2 plaid white', '1 wavy gold', '1 plaid silver'],
['posh crimson', 'contain', '3 clear crimson', '5 dotted silver', '3 dull crimson', '5 wavy violet'],
['mirrored tan', 'contain', '1 plaid white', '3 vibrant beige', '3 drab silver', '1 pale blue'],
['dull turquoise', 'contain', '5 plaid magenta', '3 bright aqua', '1 dim purple', '1 wavy orange'],
['dark tomato', 'contain', '1 plaid gray'],
['shiny red', 'contain', '4 vibrant maroon', '5 faded bronze'],
['clear tan', 'contain', '4 pale lime', '4 faded plum'],
['mirrored plum', 'contain', '1 wavy silver', '4 dim purple', '3 dim coral'],
['dotted orange', 'contain', '4 pale aqua', '3 dotted aqua', '4 clear beige'],
['wavy lime', 'contain', '5 dim salmon', '4 dark violet', '4 clear turquoise'],
['faded gray', 'contain', '2 dotted lime', '5 plaid tomato'],
['pale orange', 'contain', '5 faded maroon'],
['shiny lime', 'contain', '3 striped olive', '5 light fuchsia', '1 pale crimson', '1 pale salmon'],
['drab red', 'contain', '5 muted chartreuse', '4 clear purple', '4 drab silver', '3 posh green'],
['plaid plum', 'contain', '2 dim blue', '1 dim coral'],
['clear red', 'contain', '3 plaid teal', '4 vibrant orange', '1 pale red'],
['dark yellow', 'contain', '5 mirrored lavender', '5 dull bronze', '4 pale salmon', '5 wavy crimson'],
['clear violet', 'contain', '5 clear turquoise', '3 clear beige', '4 dim plum'],
['plaid cyan', 'contain', 'no other'],
['light salmon', 'contain', '3 dull yellow', '2 vibrant violet', '2 dark orange', '1 light magenta'],
['dim indigo', 'contain', '2 vibrant orange', '3 drab teal', '4 plaid indigo'],
['shiny magenta', 'contain', '1 dark salmon', '4 shiny gray', '2 mirrored purple'],
['drab coral', 'contain', '5 pale crimson', '1 mirrored aqua', '4 light red'],
['muted blue', 'contain', '1 dark green', '5 muted salmon', '4 posh beige', '4 pale salmon'],
['plaid salmon', 'contain', '5 striped white', '4 posh fuchsia', '5 faded turquoise'],
['vibrant bronze', 'contain', '1 bright orange', '2 bright plum'],
['dull salmon', 'contain', '2 pale crimson', '3 dark tan', '5 light plum'],
['striped magenta', 'contain', '4 wavy yellow', '3 bright chartreuse', '5 plaid cyan'],
['light olive', 'contain', '5 vibrant beige', '3 faded tomato', '1 dark indigo'],
['faded turquoise', 'contain', '2 shiny salmon', '3 wavy crimson', '5 dim yellow', '1 posh salmon'],
['pale fuchsia', 'contain', '2 posh blue', '4 mirrored blue', '3 wavy silver', '2 wavy crimson'],
['dotted tomato', 'contain', '2 dotted lime', '1 wavy teal', '1 mirrored black', '3 dull gold'],
['shiny maroon', 'contain', '5 striped salmon'],
['vibrant gray', 'contain', '5 clear tan', '5 plaid crimson', '3 striped cyan', '1 dark gold'],
['muted tomato', 'contain', '1 dull salmon'],
['striped salmon', 'contain', '4 plaid white', '5 dim salmon', '4 vibrant lime'],
['light tan', 'contain', '2 posh lavender', '5 shiny aqua'],
['wavy brown', 'contain', '2 posh lavender'],
['drab beige', 'contain', '5 plaid coral', '3 bright turquoise', '5 dark purple', '3 mirrored black'],
['bright tomato', 'contain', '1 bright teal', '2 bright tan', '2 dotted salmon'],
['dim tan', 'contain', '2 striped cyan', '5 wavy green', '3 drab beige'],
['light plum', 'contain', '4 clear silver', '1 vibrant chartreuse'],
['light black', 'contain', '1 muted tan', '2 dim yellow'],
['clear orange', 'contain', '5 mirrored violet', '1 wavy salmon', '3 dim plum'],
['bright gray', 'contain', '5 dim blue', '1 dotted red', '5 mirrored aqua'],
['striped cyan', 'contain', '4 striped teal', '1 dark tan', '1 dim green'],
['shiny olive', 'contain', '1 dark aqua', '2 muted lime'],
['clear brown', 'contain', '5 dark salmon'],
['dotted tan', 'contain', '2 plaid brown'],
['light green', 'contain', '5 plaid silver', '5 posh aqua', '3 dull green', '5 faded red'],
['posh coral', 'contain', '1 muted teal'],
['drab green', 'contain', '1 dotted blue'],
['dark fuchsia', 'contain', '2 wavy tomato', '3 faded plum'],
['vibrant purple', 'contain', '3 posh tomato', '4 dim purple', '5 plaid brown', '4 dotted red'],
['vibrant tomato', 'contain', '5 wavy orange', '1 striped teal'],
['faded coral', 'contain', '5 dotted maroon', '2 light tan', '1 plaid black', '4 dark indigo'],
['posh gold', 'contain', '4 mirrored plum'],
['muted beige', 'contain', '2 pale brown', '4 dull black', '4 vibrant blue'],
['dull green', 'contain', '3 drab silver', '5 dotted red', '3 mirrored violet', '3 bright black'],
['dark lime', 'contain', '5 light chartreuse', '3 pale magenta', '1 dull indigo'],
['dark orange', 'contain', '1 dark crimson', '2 clear turquoise', '2 dotted silver'],
['muted yellow', 'contain', '2 pale salmon', '3 bright plum', '3 shiny aqua', '5 plaid cyan'],
['vibrant white', 'contain', '5 dim coral', '5 dim bronze'],
['posh white', 'contain', '2 wavy blue', '3 clear chartreuse', '1 wavy coral', '5 drab turquoise'],
['faded violet', 'contain', '4 dim bronze'],
['bright yellow', 'contain', '5 pale violet', '2 striped fuchsia'],
['dim blue', 'contain', '2 posh salmon', '4 posh red', '5 clear turquoise', '4 muted lavender'],
['plaid olive', 'contain', 'no other'],
['posh plum', 'contain', '2 drab turquoise', '4 bright fuchsia', '4 drab indigo'],
['posh violet', 'contain', '3 plaid olive', '2 posh teal', '1 posh purple'],
['pale beige', 'contain', '4 wavy crimson', '5 shiny gold'],
['shiny turquoise', 'contain', '5 dark gray', '4 clear brown'],
['clear bronze', 'contain', '1 dull coral', '1 mirrored cyan', '2 dotted orange', '1 plaid magenta'],
['dark magenta', 'contain', '3 vibrant orange', '1 dull lime', '1 dim plum'],
['light silver', 'contain', '2 posh coral'],
['drab gold', 'contain', '5 mirrored gold', '1 bright blue'],
['dull fuchsia', 'contain', '3 pale blue'],
['muted brown', 'contain', '4 drab fuchsia', '4 plaid bronze'],
['bright coral', 'contain', '2 dull crimson'],
['clear black', 'contain', '5 striped brown'],
['mirrored coral', 'contain', '2 striped brown', '4 clear coral'],
['dull purple', 'contain', '1 plaid green', '5 shiny gold'],
['drab brown', 'contain', '4 striped coral', '1 muted magenta', '4 faded red'],
['faded plum', 'contain', '5 shiny orange'],
['vibrant violet', 'contain', '1 drab gold', '1 light violet'],
['clear salmon', 'contain', '5 posh orange', '1 wavy fuchsia', '5 mirrored yellow'],
['dull yellow', 'contain', '5 light orange', '4 striped purple'],
['striped olive', 'contain', '1 plaid beige', '1 shiny turquoise', '2 drab gold', '1 pale lime'],
['clear beige', 'contain', 'no other'],
['mirrored fuchsia', 'contain', '1 clear olive', '3 pale aqua'],
['posh turquoise', 'contain', '5 pale crimson', '3 dull cyan'],
['dull lime', 'contain', '3 plaid chartreuse'],
['wavy black', 'contain', '3 dull salmon', '5 plaid teal'],
['dim lavender', 'contain', '1 dark gray', '2 muted indigo'],
['wavy yellow', 'contain', '2 striped turquoise'],
['striped gray', 'contain', '3 drab white'],
['dotted magenta', 'contain', '3 plaid white', '4 clear beige', '1 faded maroon', '3 muted lavender'],
['vibrant coral', 'contain', '5 shiny olive', '2 pale brown'],
['dim aqua', 'contain', '5 striped crimson', '3 bright lavender'],
['pale lavender', 'contain', '3 vibrant tan'],
['bright fuchsia', 'contain', '2 dotted fuchsia'],
['dark black', 'contain', '5 drab purple', '3 striped yellow', '2 posh tan'],
['dark teal', 'contain', '3 plaid white', '5 bright cyan', '1 posh blue', '4 mirrored magenta'],
['plaid brown', 'contain', '3 bright plum', '1 muted magenta', '4 clear gray', '2 clear crimson'],
['mirrored magenta', 'contain', 'no other'],
['light brown', 'contain', '4 wavy red', '2 faded white'],
['dotted purple', 'contain', '2 pale lime'],
['clear teal', 'contain', '3 plaid red', '3 striped coral', '4 mirrored black', '2 posh red'],
['striped gold', 'contain', '3 bright plum', '2 mirrored gold'],
['dotted black', 'contain', '2 clear crimson', '1 dark violet', '2 clear teal', '3 mirrored purple'],
['dim gray', 'contain', '1 dotted salmon', '2 dim silver', '5 wavy black', '2 dotted green'],
['shiny black', 'contain', '3 plaid bronze', '5 dim plum', '3 muted teal', '5 muted magenta'],
['plaid orange', 'contain', '5 plaid crimson', '4 muted white', '4 dark lime', '5 plaid cyan'],
['striped fuchsia', 'contain', '1 dull bronze', '1 wavy aqua', '1 plaid salmon', '2 faded cyan'],
['wavy white', 'contain', '4 posh beige'],
['dull teal', 'contain', '1 vibrant blue', '1 light red', '3 striped brown'],
['vibrant chartreuse', 'contain', '1 shiny aqua', '4 clear crimson', '1 faded red', '1 dull crimson'],
['wavy cyan', 'contain', '5 striped red', '1 shiny magenta'],
['vibrant olive', 'contain', '3 light fuchsia', '5 pale tan', '5 light tomato'],
['dotted fuchsia', 'contain', '5 clear silver', '5 light aqua', '5 posh beige'],
['wavy tomato', 'contain', '2 wavy tan', '3 muted lavender', '2 pale salmon'],
['posh lime', 'contain', '4 drab lime', '4 dull lavender'],
['shiny white', 'contain', '1 plaid olive', '2 faded white', '2 dull salmon'],
['bright plum', 'contain', '1 dotted salmon', '4 plaid red', '1 mirrored purple', '3 shiny aqua'],
['dotted lavender', 'contain', '1 light green', '3 light magenta'],
['bright gold', 'contain', '4 dim blue', '5 dark salmon', '2 posh crimson'],
['striped violet', 'contain', '4 posh plum', '1 drab crimson', '2 faded orange', '3 dotted green'],
['dull plum', 'contain', '1 dark maroon'],
['striped tomato', 'contain', '5 striped maroon', '1 plaid turquoise'],
['muted bronze', 'contain', '1 plaid red'],
['dull lavender', 'contain', '2 plaid white'],
['dark bronze', 'contain', '1 clear turquoise', '5 dim purple', '2 bright turquoise', '2 striped coral'],
['muted green', 'contain', '3 plaid white', '5 pale blue', '3 plaid tan', '2 clear turquoise'],
['mirrored bronze', 'contain', '2 faded white', '3 bright teal', '2 clear red', '2 clear crimson'],
['clear silver', 'contain', '5 dim yellow', '2 striped brown', '1 muted magenta'],
['dark indigo', 'contain', '3 faded maroon', '3 mirrored purple'],
['posh silver', 'contain', '3 dotted maroon', '1 striped indigo', '1 faded red'],
['light teal', 'contain', '1 vibrant beige', '1 striped plum', '4 dim salmon'],
['dull orange', 'contain', '2 shiny teal', '5 muted teal', '1 dark fuchsia', '4 bright magenta'],
['muted red', 'contain', '2 mirrored magenta'],
['dotted gray', 'contain', '3 dull maroon', '4 mirrored blue', '3 mirrored red'],
['light lime', 'contain', '5 plaid fuchsia', '4 posh plum'],
['pale coral', 'contain', '3 shiny gray', '2 plaid beige'],
['dim brown', 'contain', '1 faded gray'],
['drab tan', 'contain', '5 dotted crimson'],
['clear chartreuse', 'contain', '4 faded maroon', '5 plaid white'],
['posh maroon', 'contain', '1 clear beige', '5 light black'],
['mirrored blue', 'contain', '4 faded gray', '5 mirrored olive', '1 pale lime'],
['clear coral', 'contain', '1 plaid fuchsia', '4 drab yellow', '4 light bronze'],
['mirrored orange', 'contain', '4 mirrored lavender', '3 faded orange', '4 mirrored gold', '3 dim silver'],
['pale bronze', 'contain', '4 plaid orange', '3 wavy chartreuse', '2 clear red'],
['faded yellow', 'contain', '2 posh green'],
['light magenta', 'contain', '3 clear silver', '3 pale magenta'],
['clear aqua', 'contain', '2 dark tan'],
['clear yellow', 'contain', '5 dim violet', '5 drab bronze'],
['plaid yellow', 'contain', '4 dotted salmon'],
['pale salmon', 'contain', '2 plaid olive', '5 clear beige'],
['bright magenta', 'contain', '2 shiny maroon', '1 bright maroon', '5 shiny white'],
['dull brown', 'contain', '4 posh fuchsia', '2 dotted tan'],
['muted magenta', 'contain', 'no other'],
['muted lavender', 'contain', '5 light aqua', '1 faded maroon', '4 plaid lavender'],
['dotted violet', 'contain', '2 pale red', '3 mirrored magenta'],
['wavy gray', 'contain', '5 dark indigo', '3 dim yellow', '3 posh lime', '1 wavy yellow'],
['posh beige', 'contain', '4 mirrored magenta', '1 striped brown', '1 mirrored aqua', '5 dotted silver'],
['drab crimson', 'contain', '2 faded coral', '4 light indigo', '4 dark indigo'],
['wavy magenta', 'contain', '5 clear gold', '4 dim purple', '3 pale green'],
['dim fuchsia', 'contain', '2 drab teal', '4 plaid brown', '5 faded orange'],
['faded indigo', 'contain', '2 faded orange', '4 striped turquoise', '4 pale salmon', '4 bright cyan'],
['posh yellow', 'contain', '2 pale gold', '3 posh coral', '1 dotted tan'],
['muted chartreuse', 'contain', '5 plaid brown', '3 dull green'],
['dotted plum', 'contain', '4 mirrored purple', '1 drab tan', '3 striped white'],
['clear plum', 'contain', '3 posh green'],
['striped red', 'contain', '1 striped tomato', '1 wavy fuchsia', '3 clear yellow'],
['striped aqua', 'contain', '4 posh teal', '2 bright beige'],
['dim gold', 'contain', '5 dull salmon', '3 mirrored red', '1 mirrored black'],
['mirrored brown', 'contain', '1 mirrored salmon'],
['wavy plum', 'contain', '3 shiny yellow', '5 light crimson', '5 dotted silver'],
['striped coral', 'contain', 'no other'],
['dark gray', 'contain', '4 dotted salmon', '2 clear brown', '2 posh crimson', '5 mirrored plum'],
['posh chartreuse', 'contain', '2 wavy fuchsia', '4 mirrored beige'],
['dotted gold', 'contain', '1 dark lavender', '1 striped black'],
['posh green', 'contain', '3 dotted salmon', '4 pale salmon', '3 posh red', '4 dim green'],
['plaid blue', 'contain', '2 posh green', '3 dim cyan', '5 dull bronze'],
['light lavender', 'contain', '5 muted green', '1 light violet', '5 muted plum'],
['pale plum', 'contain', '5 muted lavender', '5 light bronze', '4 plaid crimson'],
['mirrored indigo', 'contain', '4 dark violet', '2 wavy purple', '5 plaid tan'],
['dim violet', 'contain', '4 mirrored black', '4 dull lime', '3 posh crimson', '1 pale brown'],
['shiny coral', 'contain', '1 light aqua', '5 plaid olive', '4 bright turquoise'],
['dotted cyan', 'contain', '4 shiny olive', '4 light bronze', '2 dim plum'],
['mirrored teal', 'contain', '5 dim violet'],
['shiny purple', 'contain', '4 dim magenta', '2 clear white', '3 posh silver', '1 shiny turquoise'],
['shiny gray', 'contain', '5 pale lavender', '3 vibrant turquoise', '1 faded maroon', '1 bright cyan'],
['mirrored chartreuse', 'contain', '2 clear white'],
['light beige', 'contain', '5 mirrored turquoise', '5 plaid maroon', '3 light silver'],
['dull tomato', 'contain', '1 shiny gold', '4 pale blue'],
['plaid teal', 'contain', '1 dim purple', '3 striped turquoise', '3 light indigo', '2 faded red'],
['vibrant aqua', 'contain', '3 mirrored turquoise', '1 light plum', '5 clear teal', '1 dull blue'],
['dotted turquoise', 'contain', '5 bright fuchsia', '5 dim blue', '3 posh green', '3 wavy red'],
['dark lavender', 'contain', '1 mirrored lime', '2 plaid red', '2 striped white', '1 plaid tomato'],
['plaid tan', 'contain', '5 plaid white'],
['pale olive', 'contain', '1 clear salmon'],
['wavy indigo', 'contain', '1 plaid black', '1 wavy teal', '3 mirrored salmon'],
['drab chartreuse', 'contain', '2 light lime', '3 drab yellow'],
['drab blue', 'contain', '3 vibrant brown'],
['muted purple', 'contain', '2 shiny yellow'],
['muted aqua', 'contain', '4 striped white'],
['mirrored violet', 'contain', '3 wavy violet', '4 mirrored aqua'],
['bright cyan', 'contain', '3 wavy fuchsia', '2 dark coral', '1 shiny orange'],
['posh teal', 'contain', '5 bright gray', '4 faded gray', '2 plaid turquoise'],
['muted lime', 'contain', '2 striped coral', '1 dark tan', '4 plaid cyan'],
['mirrored crimson', 'contain', '4 faded violet', '1 posh purple'],
['light blue', 'contain', '2 dotted blue', '2 dark gold', '5 bright cyan', '1 light crimson'],
['dull beige', 'contain', '2 dark turquoise', '5 mirrored violet', '1 muted crimson'],
['dark cyan', 'contain', '5 muted blue'],
['dim turquoise', 'contain', '3 shiny silver', '1 pale yellow', '3 plaid chartreuse', '1 posh bronze'],
['faded brown', 'contain', '3 dim silver', '2 mirrored bronze'],
['wavy bronze', 'contain', '3 shiny tomato', '3 dim salmon'],
['pale brown', 'contain', '3 pale tan', '2 plaid olive', '2 posh lavender', '1 shiny aqua'],
['dull white', 'contain', '1 dull red', '5 dark gold', '3 striped magenta', '2 muted green'],
['plaid crimson', 'contain', '5 drab bronze', '2 pale blue'],
['bright lavender', 'contain', '1 dark bronze'],
['plaid red', 'contain', '3 striped turquoise', '4 dull crimson', '1 striped brown', '2 clear crimson'],
['muted gold', 'contain', '5 dotted black', '1 striped salmon', '3 drab purple', '5 bright red'],
['striped silver', 'contain', '3 posh black'],
['bright aqua', 'contain', '4 light orange', '3 wavy blue', '3 dull lime'],
['plaid fuchsia', 'contain', '2 shiny orange'],
['bright violet', 'contain', '1 drab turquoise', '1 dim cyan', '4 pale blue', '3 wavy blue'],
['dim white', 'contain', '1 plaid black', '5 plaid violet', '2 light gray'],
['bright tan', 'contain', '5 bright gold', '3 shiny salmon', '2 muted magenta', '1 dotted black'],
['shiny bronze', 'contain', '3 light aqua', '4 clear crimson', '1 light beige', '4 clear blue'],
['muted silver', 'contain', '4 striped lavender'],
['dull red', 'contain', '1 dim coral', '1 faded plum', '4 plaid red'],
['wavy aqua', 'contain', '2 dotted fuchsia', '2 mirrored tomato'],
['dark olive', 'contain', '4 muted yellow', '2 shiny gold', '2 posh crimson'],
['dark crimson', 'contain', '3 shiny aqua', '1 wavy black'],
['dark brown', 'contain', '2 drab lavender', '5 posh green', '4 pale turquoise'],
['pale blue', 'contain', '2 striped coral', '2 shiny gold'],
['vibrant blue', 'contain', '1 mirrored lavender', '4 dark aqua', '5 wavy coral'],
['posh cyan', 'contain', '1 dull lavender', '3 striped gray', '1 vibrant orange'],
['faded red', 'contain', '1 posh crimson', '1 wavy coral', '5 clear beige', '3 dotted silver'],
['vibrant gold', 'contain', '3 drab lavender', '5 dim magenta', '2 bright tomato', '4 light magenta'],
['shiny chartreuse', 'contain', '5 vibrant turquoise'],
['clear gray', 'contain', '4 wavy coral', '2 dark salmon', '3 dark indigo'],
['pale maroon', 'contain', '4 posh tomato', '5 bright tan'],
['light turquoise', 'contain', '3 drab fuchsia', '4 bright silver', '5 light green'],
['muted crimson', 'contain', '1 dim yellow', '4 wavy fuchsia', '2 mirrored magenta', '2 clear beige'],
['dull gray', 'contain', '2 posh green'],
['light fuchsia', 'contain', '5 dark gold', '3 plaid black', '2 bright lavender'],
['striped green', 'contain', '2 striped fuchsia', '5 dull tomato', '2 posh crimson'],
['mirrored purple', 'contain', '2 posh crimson', '2 mirrored magenta', '3 wavy violet', '1 striped coral'],
['vibrant black', 'contain', '3 clear magenta', '4 muted salmon', '5 posh blue'],
['plaid beige', 'contain', '2 dark black', '5 plaid yellow', '2 bright violet'],
['pale teal', 'contain', '3 pale crimson'],
['striped turquoise', 'contain', 'no other'],
['dim purple', 'contain', '2 dull crimson', '5 bright red'],
['faded cyan', 'contain', '5 posh aqua', '4 dull green', '3 dark olive'],
['mirrored cyan', 'contain', '5 plaid salmon', '4 dim salmon', '4 posh tomato'],
['striped purple', 'contain', '2 faded salmon', '2 bright tan', '4 drab white'],
['bright blue', 'contain', '3 light purple', '1 pale yellow'],
['faded bronze', 'contain', '1 light indigo', '3 plaid green', '5 posh orange'],
['striped white', 'contain', '4 drab indigo', '5 wavy tomato', '5 dotted fuchsia', '2 dim silver'],
['clear lime', 'contain', '2 dotted magenta', '5 striped magenta', '3 bright coral', '3 mirrored silver'],
['bright white', 'contain', '3 dim lavender'],
['dim crimson', 'contain', '1 posh black', '1 mirrored silver'],
['clear olive', 'contain', '4 vibrant purple', '3 drab lavender', '2 pale violet'],
['light coral', 'contain', '2 dotted green', '2 wavy aqua', '4 dark salmon', '3 light gold'],
['muted plum', 'contain', '5 plaid tan', '1 mirrored silver', '3 vibrant turquoise'],
['dim plum', 'contain', '4 bright plum'],
['drab bronze', 'contain', '1 light indigo', '3 striped brown', '3 clear gold', '3 clear gray'],
['plaid maroon', 'contain', '1 dotted orange', '5 light magenta', '4 faded salmon', '3 pale yellow'],
['wavy violet', 'contain', '2 dotted silver', '3 dull crimson', '5 mirrored aqua', '4 striped brown'],
['pale crimson', 'contain', '3 bright chartreuse', '4 light turquoise', '1 bright gray', '1 muted bronze'],
['mirrored aqua', 'contain', 'no other'],
['clear crimson', 'contain', '2 pale salmon', '4 mirrored magenta', '1 striped coral', '5 plaid olive'],
['dark tan', 'contain', '4 wavy silver', '4 dark aqua'],
['wavy maroon', 'contain', '3 clear gray'],
['light crimson', 'contain', '3 clear silver'],
['vibrant green', 'contain', '1 clear magenta', '1 dim white', '4 plaid black'],
['bright bronze', 'contain', '2 light brown'],
['light maroon', 'contain', '5 bright red', '2 bright tan', '5 dim silver', '4 pale salmon'],
['dark coral', 'contain', '2 light crimson'],
['pale silver', 'contain', '2 mirrored magenta', '3 posh red', '1 muted yellow', '5 dark salmon'],
['dotted crimson', 'contain', '4 faded salmon', '4 vibrant beige', '5 dim beige'],
['dull silver', 'contain', '1 striped brown', '2 shiny magenta'],
['striped beige', 'contain', '4 clear crimson'],
['faded orange', 'contain', '2 drab white', '3 striped salmon', '5 bright chartreuse'],
['drab olive', 'contain', '4 clear purple'],
['dull maroon', 'contain', '3 dotted magenta'],
['vibrant lavender', 'contain', '2 light tomato', '1 shiny teal'],
['dotted chartreuse', 'contain', '4 faded white', '2 light brown'],
['drab cyan', 'contain', '2 pale coral', '3 light purple', '2 drab bronze', '1 dim beige'],
['bright teal', 'contain', '2 vibrant plum', '2 dull tan', '1 dim tomato', '5 dark violet'],
['wavy fuchsia', 'contain', '1 dim green', '2 wavy violet'],
['drab black', 'contain', '3 striped tomato', '4 light salmon', '4 dim yellow', '3 shiny black'],
['dark green', 'contain', '5 dark tan'],
['clear tomato', 'contain', '4 mirrored gold', '4 dark gold'],
['plaid aqua', 'contain', '5 dotted coral', '1 muted white'],
['plaid white', 'contain', '3 clear crimson', '3 wavy gold', '3 pale lime', '2 striped brown'],
['muted black', 'contain', '1 wavy tan', '4 mirrored turquoise'],
['faded aqua', 'contain', '5 dull turquoise', '1 vibrant tan'],
['vibrant brown', 'contain', '5 pale silver', '3 drab orange', '1 clear olive'],
['pale cyan', 'contain', '2 faded cyan', '1 mirrored tan', '3 vibrant aqua', '3 light gold'],
['shiny salmon', 'contain', '5 posh red', '5 light chartreuse', '2 striped brown'],
['plaid lime', 'contain', '4 dim gold', '1 clear magenta'],
['drab tomato', 'contain', '5 clear orange'],
['faded beige', 'contain', '3 dark crimson', '2 mirrored tan'],
['vibrant crimson', 'contain', '4 wavy blue', '5 clear gray'],
['dotted maroon', 'contain', '5 dotted red', '4 wavy silver', '1 drab brown', '3 dark black'],
['striped indigo', 'contain', '3 striped orange'],
['dim orange', 'contain', '1 wavy lavender', '5 drab brown', '1 dull salmon'],
['posh olive', 'contain', '3 faded indigo', '1 plaid white'],
['striped lavender', 'contain', '1 bright red'],
['muted violet', 'contain', '3 bright tan', '5 striped coral', '1 drab bronze'],
['wavy tan', 'contain', '1 striped brown', '3 dim salmon', '1 posh fuchsia', '4 mirrored violet'],
['dull magenta', 'contain', '1 clear red', '4 dull green', '2 posh lime', '5 mirrored gold'],
['dotted red', 'contain', '1 mirrored black', '3 dull bronze', '2 dim salmon'],
['drab turquoise', 'contain', '5 muted yellow', '1 light indigo', '5 dotted black'],
['faded purple', 'contain', '5 dim orange', '3 dark red'],
['faded teal', 'contain', '1 bright fuchsia'],
['plaid gray', 'contain', '5 pale aqua'],
['bright black', 'contain', '4 wavy violet'],
['dim green', 'contain', '3 mirrored aqua', '1 light chartreuse', '1 light indigo'],
['dark gold', 'contain', '2 mirrored red', '2 bright lavender', '3 pale crimson'],
['dark plum', 'contain', '2 pale salmon'],
['wavy orange', 'contain', '2 light tan', '1 pale yellow', '2 shiny aqua', '4 vibrant orange'],
['bright chartreuse', 'contain', '5 dark salmon', '1 plaid olive'],
['wavy purple', 'contain', '4 faded coral', '2 vibrant orange'],
['shiny violet', 'contain', '3 plaid chartreuse', '2 plaid brown'],
['posh indigo', 'contain', '1 posh salmon'],
['clear indigo', 'contain', '3 light violet'],
['plaid purple', 'contain', '1 clear blue', '2 muted gold', '1 dull brown'],
['posh lavender', 'contain', '1 plaid black', '3 shiny orange', '3 posh red', '4 plaid cyan'],
['wavy silver', 'contain', '3 plaid cyan', '1 plaid olive'],
['posh salmon', 'contain', '3 clear gray', '5 dotted silver', '4 shiny aqua'],
['faded lavender', 'contain', '4 drab chartreuse', '4 plaid magenta', '1 vibrant tomato'],
['pale red', 'contain', '4 bright red', '4 pale lime', '3 striped turquoise'],
['bright purple', 'contain', '3 muted lavender'],
['dim magenta', 'contain', '1 plaid teal', '3 posh lavender'],
['posh magenta', 'contain', '3 pale teal', '5 mirrored tomato', '2 striped gold', '2 bright tomato'],
['bright brown', 'contain', '1 dark fuchsia', '4 pale yellow', '5 shiny crimson'],
['light red', 'contain', '1 wavy teal'],
['pale turquoise', 'contain', '3 mirrored yellow'],
['vibrant magenta', 'contain', '4 dark gold'],
['dotted salmon', 'contain', '3 wavy violet', '4 shiny aqua', '4 dull bronze'],
['mirrored gray', 'contain', '3 dark plum', '3 striped gray', '4 plaid violet'],
['dim yellow', 'contain', '3 striped turquoise', '2 pale salmon', '4 mirrored magenta', '5 striped brown'],
['drab lavender', 'contain', '2 faded maroon', '2 shiny orange'],
['muted maroon', 'contain', '1 wavy tomato', '2 drab red'],
['clear gold', 'contain', '3 mirrored olive', '3 striped turquoise'],
['light bronze', 'contain', '1 muted lavender'],
['dotted bronze', 'contain', '2 dotted turquoise'],
['pale tomato', 'contain', '3 shiny beige', '1 mirrored tomato', '2 dotted maroon', '2 wavy teal'],
['pale chartreuse', 'contain', '5 plaid silver'],
['drab magenta', 'contain', '5 wavy tomato', '1 drab brown', '2 posh maroon', '5 mirrored teal'],
['posh blue', 'contain', '3 muted lime', '1 mirrored tomato', '5 shiny aqua'],
['posh purple', 'contain', '5 dull maroon'],
['posh bronze', 'contain', '2 mirrored orange', '2 pale violet', '2 plaid gray'],
['pale gold', 'contain', '4 striped brown', '2 muted green'],
['faded crimson', 'contain', '5 drab salmon', '2 posh crimson', '3 light purple', '5 clear red'],
['vibrant fuchsia', 'contain', '2 posh beige', '4 dotted indigo', '5 pale silver', '4 clear black'],
['faded lime', 'contain', '3 posh plum', '3 shiny aqua', '4 dull chartreuse'],
['shiny fuchsia', 'contain', '4 shiny salmon', '3 pale chartreuse'],
['wavy lavender', 'contain', '2 dark blue', '5 muted salmon'],
['pale indigo', 'contain', '1 wavy gold', '1 clear silver', '3 dim blue'],
['drab violet', 'contain', '4 muted yellow'],
['shiny plum', 'contain', '3 bright black', '5 pale teal', '5 light red', '2 plaid magenta'],
['shiny gold', 'contain', '1 vibrant chartreuse'],
['wavy gold', 'contain', '5 posh beige', '1 mirrored aqua'],
['dark salmon', 'contain', '3 light aqua', '3 posh red', '2 mirrored black', '1 posh crimson'],
['pale tan', 'contain', '4 wavy coral'],
['dull tan', 'contain', '4 bright cyan'],
['clear maroon', 'contain', '4 dim magenta', '2 shiny lavender'],
['light white', 'contain', '3 dark brown', '4 bright fuchsia'],
['wavy red', 'contain', '4 dim red'],
['dotted aqua', 'contain', '4 striped teal'],
['bright beige', 'contain', '5 shiny tomato'],
['plaid indigo', 'contain', '1 muted bronze'],
['light yellow', 'contain', '2 striped black', '2 muted gold', '3 dotted tan', '5 dark coral'],
['vibrant silver', 'contain', '2 dim blue'],
['posh tomato', 'contain', '5 bright red', '3 posh red', '3 plaid olive', '4 clear crimson'],
['pale magenta', 'contain', '3 mirrored blue', '5 dull maroon', '5 dark violet'],
['light indigo', 'contain', '2 plaid olive', '1 plaid black', '3 dark indigo'],
['shiny green', 'contain', '1 vibrant chartreuse', '4 bright lavender', '3 wavy crimson', '4 dull red'],
['striped maroon', 'contain', '2 posh coral', '2 striped gray', '3 clear plum'],
['posh fuchsia', 'contain', '2 wavy gold', '2 posh beige'],
['dim coral', 'contain', '4 wavy gold', '4 muted lavender'],
['faded maroon', 'contain', '5 dim purple', '4 bright red', '5 wavy violet', '1 mirrored aqua'],
['striped black', 'contain', '4 plaid fuchsia', '5 bright lavender', '4 dull black'],
['mirrored gold', 'contain', '3 dotted silver'],
['light tomato', 'contain', '5 pale brown', '3 wavy coral'],
['dark white', 'contain', '2 mirrored tomato', '1 striped orange', '1 dim olive', '2 dotted blue'],
['dotted green', 'contain', '3 clear plum'],
['dotted brown', 'contain', '1 clear magenta'],
['muted orange', 'contain', '3 muted olive', '2 faded yellow', '2 faded turquoise', '3 muted violet'],
['dull olive', 'contain', '2 dotted teal'],
['mirrored lime', 'contain', '4 dark violet', '4 muted yellow'],
['wavy green', 'contain', '5 bright lime'],
['drab purple', 'contain', '2 striped turquoise', '4 clear silver', '1 muted lime'],
['clear cyan', 'contain', '5 light lavender'],
['dim black', 'contain', '3 dull black'],
['posh gray', 'contain', '4 mirrored magenta'],
['dotted yellow', 'contain', '4 light maroon', '1 clear blue', '5 dark maroon'],
['mirrored olive', 'contain', '2 dark violet', '2 dull crimson', '5 dim salmon', '5 bright tan'],
['dark blue', 'contain', '3 dull aqua', '1 dim teal'],
['dull bronze', 'contain', '4 striped coral'],
['drab maroon', 'contain', '2 dark bronze', '1 wavy blue'],
['mirrored lavender', 'contain', '4 clear black'],
['dim beige', 'contain', '3 shiny silver', '2 dark purple', '3 dull green'],
['light violet', 'contain', '1 muted gray', '5 wavy tomato'],
['striped chartreuse', 'contain', '3 dull tan', '1 dim salmon'],
['posh red', 'contain', '2 clear crimson', '2 striped coral', '2 bright red'],
['wavy beige', 'contain', '5 muted silver', '5 pale teal'],
['light gray', 'contain', '5 drab indigo', '3 posh crimson', '1 dark tan', '2 pale red'],
['muted white', 'contain', '3 wavy fuchsia'],
['pale violet', 'contain', '4 wavy tan', '2 plaid yellow'],
['drab fuchsia', 'contain', '1 plaid lavender', '2 pale lime'],
['clear green', 'contain', '4 light indigo'],
['vibrant turquoise', 'contain', '2 vibrant tan', '3 clear silver'],
['faded green', 'contain', '5 striped orange', '4 bright fuchsia'],
['striped tan', 'contain', '4 wavy silver'],
['clear white', 'contain', '3 vibrant fuchsia', '2 pale silver', '1 vibrant indigo', '3 shiny silver'],
['dim cyan', 'contain', '2 mirrored black', '2 plaid chartreuse', '4 bright gold'],
['muted gray', 'contain', '3 mirrored violet', '4 dim yellow'],
['mirrored maroon', 'contain', '5 clear crimson', '2 clear gray', '1 dotted salmon'],
['dim bronze', 'contain', '2 striped plum', '2 bright orange'],
['shiny tomato', 'contain', '4 dim yellow', '2 faded bronze', '1 drab maroon', '3 dim gold'],
['muted olive', 'contain', '2 mirrored yellow', '4 bright olive'],
['shiny brown', 'contain', '3 bright coral'],
['clear blue', 'contain', '2 pale green', '2 light violet', '4 plaid crimson'],
['faded tan', 'contain', '4 dim crimson', '3 mirrored turquoise', '3 drab gold'],
['muted cyan', 'contain', '2 drab silver'],
['mirrored red', 'contain', '1 bright gold'],
['faded salmon', 'contain', '5 posh red', '4 dull crimson', '3 dotted salmon', '5 shiny olive'],
['dark purple', 'contain', '5 dim magenta'],
['dotted lime', 'contain', '4 posh fuchsia', '3 wavy tan', '2 mirrored aqua', '1 shiny aqua'],
['posh tan', 'contain', '3 plaid tan', '2 drab fuchsia'],
['dotted teal', 'contain', '4 dull crimson', '2 bright lavender', '2 wavy tan', '4 muted crimson'],
['clear purple', 'contain', '4 shiny aqua', '1 dim cyan', '3 dotted black', '4 dull gray'],
['light gold', 'contain', '2 dotted magenta', '5 dark olive', '3 dim cyan', '2 dark indigo'],
['mirrored silver', 'contain', '2 plaid black', '3 vibrant beige', '3 mirrored purple', '3 dotted lime'],
['posh black', 'contain', '4 wavy violet', '3 plaid teal'],
['faded silver', 'contain', '2 vibrant purple', '5 shiny olive'],
['drab teal', 'contain', '2 dotted salmon', '4 posh beige', '4 mirrored tan', '1 muted green'],
['dark maroon', 'contain', '2 dark tan', '5 mirrored gold', '2 dim plum'],
['striped plum', 'contain', '3 striped coral', '5 clear brown', '1 striped brown'],
['striped bronze', 'contain', '4 drab yellow', '4 striped chartreuse', '5 posh plum', '3 clear blue'],
['drab plum', 'contain', '1 shiny gold', '5 vibrant tan', '3 light gold'],
['clear fuchsia', 'contain', '1 vibrant red'],
['dark silver', 'contain', '5 clear salmon', '1 faded yellow', '1 shiny lavender', '3 wavy fuchsia'],
['striped lime', 'contain', '2 dim tomato', '3 light fuchsia', '1 light lime'],
['wavy salmon', 'contain', '1 shiny tomato', '1 light tomato'],
['dim maroon', 'contain', '4 faded beige', '2 bright turquoise', '4 dull purple', '4 vibrant olive'],
['faded chartreuse', 'contain', '4 mirrored blue', '5 posh white', '2 wavy magenta'],
['clear magenta', 'contain', '2 muted bronze', '5 dim yellow', '2 dotted lime'],
['bright silver', 'contain', '2 bright gold', '4 wavy yellow'],
['dull violet', 'contain', '3 faded beige', '1 mirrored orange', '1 mirrored aqua'],
['vibrant cyan', 'contain', '2 clear aqua', '2 dark maroon', '5 pale tan'],
['light chartreuse', 'contain', '1 wavy gold', '2 posh tomato', '2 clear silver'],
['dotted olive', 'contain', '5 wavy crimson', '1 drab tomato'],
['posh aqua', 'contain', '3 striped brown'],
['posh orange', 'contain', '2 wavy coral'],
['dull cyan', 'contain', '1 dark tan', '5 dull gray', '3 drab turquoise', '4 shiny aqua'],
['muted teal', 'contain', '4 dull blue'],
['bright turquoise', 'contain', '5 dull bronze', '1 plaid lavender'],
['plaid tomato', 'contain', '2 muted lime', '1 light indigo', '5 posh tomato'],
['dim salmon', 'contain', '1 dark indigo', '5 plaid brown', '3 clear crimson', '4 clear silver'],
['posh brown', 'contain', '3 clear silver', '5 faded cyan', '4 posh crimson'],
['dark turquoise', 'contain', '1 drab crimson', '5 striped coral'],
['dull crimson', 'contain', 'no other'],
['striped teal', 'contain', '5 plaid lavender', '4 faded red'],
['dotted blue', 'contain', '5 muted beige'],
['vibrant plum', 'contain', '1 pale lime', '1 posh red', '1 dull bronze', '3 drab silver'],
['wavy coral', 'contain', '4 mirrored magenta', '5 dim yellow', '4 bright red', '2 posh crimson'],
['dark chartreuse', 'contain', '5 dotted fuchsia', '3 mirrored silver', '5 mirrored aqua', '4 dim cyan'],
['vibrant teal', 'contain', '3 vibrant silver'],
['shiny beige', 'contain', '5 posh teal'],
['dim olive', 'contain', '3 clear gray', '4 wavy gold'],
['drab yellow', 'contain', '4 light chartreuse', '3 striped crimson', '2 faded gray'],
['dull chartreuse', 'contain', '1 light lavender'],
['dotted silver', 'contain', 'no other'],
['shiny blue', 'contain', '5 dull brown', '2 dark coral', '4 shiny crimson'],
['mirrored black', 'contain', '5 mirrored magenta', '1 striped turquoise', '2 plaid cyan'],
['dull black', 'contain', '4 dim purple', '4 dark salmon', '2 mirrored gold'],
['mirrored beige', 'contain', '4 striped fuchsia', '4 plaid black', '5 dim red', '5 light green'],
['dim chartreuse', 'contain', '4 shiny yellow'],
['shiny teal', 'contain', '1 vibrant maroon'],
['dim tomato', 'contain', '5 plaid tomato', '5 mirrored violet', '2 mirrored orange'],
['vibrant beige', 'contain', '1 plaid black', '3 dotted salmon', '2 posh fuchsia'],
['dull aqua', 'contain', '5 wavy tan', '3 bright olive'],
['pale lime', 'contain', '5 bright turquoise', '5 dim yellow', '3 shiny orange'],
['bright orange', 'contain', '4 muted gold', '1 clear white'],
['drab salmon', 'contain', '2 dark fuchsia', '2 dull gray'],
['mirrored salmon', 'contain', '3 posh plum', '1 dotted silver', '1 clear plum', '5 dull black'],
['shiny silver', 'contain', '4 drab lavender', '2 dim violet', '5 dark aqua', '2 vibrant chartreuse'],
['plaid coral', 'contain', '4 dim blue', '1 vibrant lime'],
['mirrored white', 'contain', '2 pale gold', '3 shiny green', '5 striped white'],
['pale gray', 'contain', '5 mirrored gold', '1 wavy silver', '5 posh green', '1 mirrored red'],
['pale white', 'contain', '4 shiny turquoise', '4 bright plum', '5 dotted bronze'],
['muted fuchsia', 'contain', '5 plaid turquoise', '2 dark aqua', '4 pale brown', '4 striped plum'],
['striped yellow', 'contain', '5 posh red', '1 plaid black'],
['plaid silver', 'contain', '2 dark indigo', '3 clear teal', '3 dotted black'],
['plaid black', 'contain', '3 dull crimson'],
['vibrant lime', 'contain', '1 dotted fuchsia', '4 dull bronze', '4 dark aqua', '1 dark salmon'],
['dotted white', 'contain', '5 dim red'],
['light aqua', 'contain', '5 mirrored aqua', '2 striped brown', '4 posh crimson'],
['striped brown', 'contain', '1 dotted silver', '5 clear beige'],
['vibrant red', 'contain', '3 bright olive', '3 plaid chartreuse', '3 light olive', '4 dim violet'],
['dim teal', 'contain', '3 clear violet'],
['bright lime', 'contain', '2 dull lavender', '4 pale turquoise'],
['striped crimson', 'contain', '5 bright gray', '4 dark green', '4 posh plum', '5 shiny coral'],
['mirrored tomato', 'contain', '1 wavy tan'],
['dull blue', 'contain', '5 bright turquoise', '2 striped brown'],
['mirrored yellow', 'contain', '4 vibrant purple', '4 faded bronze', '2 dull lavender', '3 light plum'],
['plaid gold', 'contain', '5 striped olive', '5 dotted chartreuse'],
['dotted coral', 'contain', '2 bright teal'],
['wavy crimson', 'contain', '5 dotted salmon', '1 dull crimson'],
['dark aqua', 'contain', '3 dull crimson', '5 light aqua', '3 mirrored purple', '1 striped brown'],
['vibrant yellow', 'contain', '1 faded beige', '3 dark brown', '1 wavy bronze'],
['wavy teal', 'contain', '5 dotted magenta'],
['drab white', 'contain', '3 pale blue'],
['muted salmon', 'contain', '4 posh salmon', '1 bright chartreuse'],
['light purple', 'contain', '5 dark maroon'],
['faded black', 'contain', '4 dull gold'],
['muted turquoise', 'contain', '1 wavy silver', '4 clear purple'],
['plaid chartreuse', 'contain', '1 posh crimson', '5 striped brown'],
['vibrant tan', 'contain', '2 dull blue', '1 posh black', '1 faded red', '5 plaid magenta'],
['shiny orange', 'contain', '5 vibrant chartreuse', '3 shiny gold'],
['shiny lavender', 'contain', '2 posh teal'],
['pale black', 'contain', '5 dark brown'],
['shiny cyan', 'contain', '5 wavy tomato', '3 bright bronze', '3 faded crimson'],
['faded olive', 'contain', '3 clear aqua'],
['dark violet', 'contain', '4 faded red'],
['light orange', 'contain', '1 posh aqua', '2 light crimson', '2 dark maroon'],
['drab silver', 'contain', '1 pale blue'],
['plaid bronze', 'contain', '5 mirrored orange', '4 plaid cyan', '1 dotted black'],
['plaid violet', 'contain', '1 plaid fuchsia', '5 clear teal'],
['clear turquoise', 'contain', '4 dim yellow', '5 plaid teal', '3 plaid red', '1 dotted salmon'],
['plaid lavender', 'contain', '3 clear silver', '4 dull bronze'],
['mirrored green', 'contain', '3 striped lavender'],
['faded white', 'contain', '2 light chartreuse'],
['bright crimson', 'contain', '2 mirrored purple'],
['dotted beige', 'contain', '1 pale salmon', '5 dotted teal', '5 light lavender', '3 wavy violet'],
['pale green', 'contain', '2 dark gold', '4 clear gray'],
['dull indigo', 'contain', '2 striped brown', '3 plaid plum'],
['shiny yellow', 'contain', '3 striped silver', '2 mirrored plum', '1 muted red', '5 clear gold'],
['bright maroon', 'contain', '2 muted crimson', '2 plaid chartreuse', '1 dim violet', '1 plaid blue'],
['vibrant orange', 'contain', '5 posh plum', '4 shiny gold'],
['faded fuchsia', 'contain', '2 dotted aqua'],
['bright indigo', 'contain', '3 shiny coral', '1 muted salmon', '2 clear white', '1 vibrant maroon'],
['shiny indigo', 'contain', '4 dark red', '2 pale lime'],
['light cyan', 'contain', '2 clear black', '2 mirrored aqua', '1 faded beige', '2 faded salmon'],
['faded gold', 'contain', '5 muted lime', '3 plaid fuchsia'],
['muted coral', 'contain', '2 faded indigo', '1 dim beige', '5 dotted orange', '4 posh black'],
['drab gray', 'contain', '5 clear magenta', '5 bright tomato', '1 dull gold'],
['vibrant salmon', 'contain', '4 bright gold'],
['dark red', 'contain', '5 posh black', '4 faded teal'],
['wavy blue', 'contain', '3 dim green', '4 dull green', '2 posh aqua'],
['mirrored turquoise', 'contain', '5 dull lime', '4 dark gray', '1 striped cyan', '4 muted gold'],
['wavy chartreuse', 'contain', '1 pale brown', '4 shiny chartreuse', '4 wavy fuchsia'],
['dim red', 'contain', '1 bright blue', '3 clear purple', '2 wavy crimson', '5 shiny black'],
['dull gold', 'contain', '4 wavy blue'],
['faded blue', 'contain', '1 plaid turquoise', '2 vibrant indigo'],
['shiny aqua', 'contain', '4 plaid cyan', '4 posh crimson'],
['bright salmon', 'contain', '1 posh red', '1 shiny orange', '1 vibrant crimson'],
['pale yellow', 'contain', '4 plaid cyan'],
['plaid magenta', 'contain', '3 plaid brown', '5 pale yellow', '5 drab fuchsia', '1 clear black'],
['vibrant maroon', 'contain', '4 dull tomato', '1 dotted indigo', '2 plaid teal', '2 shiny gold'],
['drab orange', 'contain', '3 wavy coral'],
['pale aqua', 'contain', '5 wavy lime', '5 drab turquoise'],
['shiny crimson', 'contain', '3 posh black', '5 drab fuchsia', '1 plaid fuchsia', '4 posh plum'],
['pale purple', 'contain', '2 clear green', '2 striped crimson', '4 drab indigo'],
['faded magenta', 'contain', '5 light red'],
['shiny tan', 'contain', '5 plaid silver', '3 light lavender', '4 wavy purple'],
['vibrant indigo', 'contain', '5 plaid beige'],
['wavy turquoise', 'contain', '4 dark teal', '2 dark cyan', '4 mirrored olive', '5 bright red'],
['striped blue', 'contain', '1 vibrant lime', '3 vibrant indigo', '1 pale maroon', '2 dark white'],
['faded tomato', 'contain', '3 plaid tan', '4 pale tan', '5 wavy violet', '3 pale lime'],
['bright green', 'contain', '1 bright purple', '5 posh magenta'],
['dark beige', 'contain', '4 light green', '4 light magenta', '5 dotted lime', '4 plaid salmon'],
['plaid green', 'contain', '2 pale salmon'],
['bright red', 'contain', '2 dotted silver'],
['drab lime', 'contain', '3 dotted bronze'],
['muted indigo', 'contain', '4 posh gray', '2 dark lavender', '2 plaid chartreuse', '2 pale red'],
['muted tan', 'contain', '2 muted brown', '3 dull maroon'],
['plaid turquoise', 'contain', '3 clear teal', '2 dull tomato', '5 dotted purple', '1 posh salmon'],
['drab aqua', 'contain', '3 bright lime', '5 posh red']]