bags_list = [
['dim silver', 'contain', 'posh fuchsia'],
['wavy olive', 'contain', 'striped olive', 'dull cyan'],
['dull coral', 'contain', 'dim olive', 'muted violet', 'dark gray'],
['bright olive', 'contain', 'light indigo', 'dark coral'],
['clear lavender', 'contain', 'dark olive'],
['dim lime', 'contain', 'dotted red'],
['drab indigo', 'contain', 'striped coral', 'muted bronze'],
['striped orange', 'contain', 'wavy fuchsia', 'clear red', 'plaid red'],
['dotted indigo', 'contain', 'plaid white', 'wavy gold', 'plaid silver'],
['posh crimson', 'contain', 'clear crimson', 'dotted silver', 'dull crimson', 'wavy violet'],
['mirrored tan', 'contain', 'plaid white', 'vibrant beige', 'drab silver', 'pale blue'],
['dull turquoise', 'contain', 'plaid magenta', 'bright aqua', 'dim purple', 'wavy orange'],
['dark tomato', 'contain', 'plaid gray'],
['shiny red', 'contain', 'vibrant maroon', 'faded bronze'],
['clear tan', 'contain', 'pale lime', 'faded plum'],
['mirrored plum', 'contain', 'wavy silver', 'dim purple', 'dim coral'],
['dotted orange', 'contain', 'pale aqua', 'dotted aqua', 'clear beige'],
['wavy lime', 'contain', 'dim salmon', 'dark violet', 'clear turquoise'],
['faded gray', 'contain', 'dotted lime', 'plaid tomato'],
['pale orange', 'contain', 'faded maroon'],
['shiny lime', 'contain', 'striped olive', 'light fuchsia', 'pale crimson', 'pale salmon'],
['drab red', 'contain', 'muted chartreuse', 'clear purple', 'drab silver', 'posh green'],
['plaid plum', 'contain', 'dim blue', 'dim coral'],
['clear red', 'contain', 'plaid teal', 'vibrant orange', 'pale red'],
['dark yellow', 'contain', 'mirrored lavender', 'dull bronze', 'pale salmon', 'wavy crimson'],
['clear violet', 'contain', 'clear turquoise', 'clear beige', 'dim plum'],
['plaid cyan', 'contain', 'no other'],
['light salmon', 'contain', 'dull yellow', 'vibrant violet', 'dark orange', 'light magenta'],
['dim indigo', 'contain', 'vibrant orange', 'drab teal', 'plaid indigo'],
['shiny magenta', 'contain', 'dark salmon', 'shiny gray', 'mirrored purple'],
['drab coral', 'contain', 'pale crimson', 'mirrored aqua', 'light red'],
['muted blue', 'contain', 'dark green', 'muted salmon', 'posh beige', 'pale salmon'],
['plaid salmon', 'contain', 'striped white', 'posh fuchsia', 'faded turquoise'],
['vibrant bronze', 'contain', 'bright orange', 'bright plum'],
['dull salmon', 'contain', 'pale crimson', 'dark tan', 'light plum'],
['striped magenta', 'contain', 'wavy yellow', 'bright chartreuse', 'plaid cyan'],
['light olive', 'contain', 'vibrant beige', 'faded tomato', 'dark indigo'],
['faded turquoise', 'contain', 'shiny salmon', 'wavy crimson', 'dim yellow', 'posh salmon'],
['pale fuchsia', 'contain', 'posh blue', 'mirrored blue', 'wavy silver', 'wavy crimson'],
['dotted tomato', 'contain', 'dotted lime', 'wavy teal', 'mirrored black', 'dull gold'],
['shiny maroon', 'contain', 'striped salmon'],
['vibrant gray', 'contain', 'clear tan', 'plaid crimson', 'striped cyan', 'dark gold'],
['muted tomato', 'contain', 'dull salmon'],
['striped salmon', 'contain', 'plaid white', 'dim salmon', 'vibrant lime'],
['light tan', 'contain', 'posh lavender', 'shiny aqua'],
['wavy brown', 'contain', 'posh lavender'],
['drab beige', 'contain', 'plaid coral', 'bright turquoise', 'dark purple', 'mirrored black'],
['bright tomato', 'contain', 'bright teal', 'bright tan', 'dotted salmon'],
['dim tan', 'contain', 'striped cyan', 'wavy green', 'drab beige'],
['light plum', 'contain', 'clear silver', 'vibrant chartreuse'],
['light black', 'contain', 'muted tan', 'dim yellow'],
['clear orange', 'contain', 'mirrored violet', 'wavy salmon', 'dim plum'],
['bright gray', 'contain', 'dim blue', 'dotted red', 'mirrored aqua'],
['striped cyan', 'contain', 'striped teal', 'dark tan', 'dim green'],
['shiny olive', 'contain', 'dark aqua', 'muted lime'],
['clear brown', 'contain', 'dark salmon'],
['dotted tan', 'contain', 'plaid brown'],
['light green', 'contain', 'plaid silver', 'posh aqua', 'dull green', 'faded red'],
['posh coral', 'contain', 'muted teal'],
['drab green', 'contain', 'dotted blue'],
['dark fuchsia', 'contain', 'wavy tomato', 'faded plum'],
['vibrant purple', 'contain', 'posh tomato', 'dim purple', 'plaid brown', 'dotted red'],
['vibrant tomato', 'contain', 'wavy orange', 'striped teal'],
['faded coral', 'contain', 'dotted maroon', 'light tan', 'plaid black', 'dark indigo'],
['posh gold', 'contain', 'mirrored plum'],
['muted beige', 'contain', 'pale brown', 'dull black', 'vibrant blue'],
['dull green', 'contain', 'drab silver', 'dotted red', 'mirrored violet', 'bright black'],
['dark lime', 'contain', 'light chartreuse', 'pale magenta', 'dull indigo'],
['dark orange', 'contain', 'dark crimson', 'clear turquoise', 'dotted silver'],
['muted yellow', 'contain', 'pale salmon', 'bright plum', 'shiny aqua', 'plaid cyan'],
['vibrant white', 'contain', 'dim coral', 'dim bronze'],
['posh white', 'contain', 'wavy blue', 'clear chartreuse', 'wavy coral', 'drab turquoise'],
['faded violet', 'contain', 'dim bronze'],
['bright yellow', 'contain', 'pale violet', 'striped fuchsia'],
['dim blue', 'contain', 'posh salmon', 'posh red', 'clear turquoise', 'muted lavender'],
['plaid olive', 'contain', 'no other'],
['posh plum', 'contain', 'drab turquoise', 'bright fuchsia', 'drab indigo'],
['posh violet', 'contain', 'plaid olive', 'posh teal', 'posh purple'],
['pale beige', 'contain', 'wavy crimson', 'shiny gold'],
['shiny turquoise', 'contain', 'dark gray', 'clear brown'],
['clear bronze', 'contain', 'dull coral', 'mirrored cyan', 'dotted orange', 'plaid magenta'],
['dark magenta', 'contain', 'vibrant orange', 'dull lime', 'dim plum'],
['light silver', 'contain', 'posh coral'],
['drab gold', 'contain', 'mirrored gold', 'bright blue'],
['dull fuchsia', 'contain', 'pale blue'],
['muted brown', 'contain', 'drab fuchsia', 'plaid bronze'],
['bright coral', 'contain', 'dull crimson'],
['clear black', 'contain', 'striped brown'],
['mirrored coral', 'contain', 'striped brown', 'clear coral'],
['dull purple', 'contain', 'plaid green', 'shiny gold'],
['drab brown', 'contain', 'striped coral', 'muted magenta', 'faded red'],
['faded plum', 'contain', 'shiny orange'],
['vibrant violet', 'contain', 'drab gold', 'light violet'],
['clear salmon', 'contain', 'posh orange', 'wavy fuchsia', 'mirrored yellow'],
['dull yellow', 'contain', 'light orange', 'striped purple'],
['striped olive', 'contain', 'plaid beige', 'shiny turquoise', 'drab gold', 'pale lime'],
['clear beige', 'contain', 'no other'],
['mirrored fuchsia', 'contain', 'clear olive', 'pale aqua'],
['posh turquoise', 'contain', 'pale crimson', 'dull cyan'],
['dull lime', 'contain', 'plaid chartreuse'],
['wavy black', 'contain', 'dull salmon', 'plaid teal'],
['dim lavender', 'contain', 'dark gray', 'muted indigo'],
['wavy yellow', 'contain', 'striped turquoise'],
['striped gray', 'contain', 'drab white'],
['dotted magenta', 'contain', 'plaid white', 'clear beige', 'faded maroon', 'muted lavender'],
['vibrant coral', 'contain', 'shiny olive', 'pale brown'],
['dim aqua', 'contain', 'striped crimson', 'bright lavender'],
['pale lavender', 'contain', 'vibrant tan'],
['bright fuchsia', 'contain', 'dotted fuchsia'],
['dark black', 'contain', 'drab purple', 'striped yellow', 'posh tan'],
['dark teal', 'contain', 'plaid white', 'bright cyan', 'posh blue', 'mirrored magenta'],
['plaid brown', 'contain', 'bright plum', 'muted magenta', 'clear gray', 'clear crimson'],
['mirrored magenta', 'contain', 'no other'],
['light brown', 'contain', 'wavy red', 'faded white'],
['dotted purple', 'contain', 'pale lime'],
['clear teal', 'contain', 'plaid red', 'striped coral', 'mirrored black', 'posh red'],
['striped gold', 'contain', 'bright plum', 'mirrored gold'],
['dotted black', 'contain', 'clear crimson', 'dark violet', 'clear teal', 'mirrored purple'],
['dim gray', 'contain', 'dotted salmon', 'dim silver', 'wavy black', 'dotted green'],
['shiny black', 'contain', 'plaid bronze', 'dim plum', 'muted teal', 'muted magenta'],
['plaid orange', 'contain', 'plaid crimson', 'muted white', 'dark lime', 'plaid cyan'],
['striped fuchsia', 'contain', 'dull bronze', 'wavy aqua', 'plaid salmon', 'faded cyan'],
['wavy white', 'contain', 'posh beige'],
['dull teal', 'contain', 'vibrant blue', 'light red', 'striped brown'],
['vibrant chartreuse', 'contain', 'shiny aqua', 'clear crimson', 'faded red', 'dull crimson'],
['wavy cyan', 'contain', 'striped red', 'shiny magenta'],
['vibrant olive', 'contain', 'light fuchsia', 'pale tan', 'light tomato'],
['dotted fuchsia', 'contain', 'clear silver', 'light aqua', 'posh beige'],
['wavy tomato', 'contain', 'wavy tan', 'muted lavender', 'pale salmon'],
['posh lime', 'contain', 'drab lime', 'dull lavender'],
['shiny white', 'contain', 'plaid olive', 'faded white', 'dull salmon'],
['bright plum', 'contain', 'dotted salmon', 'plaid red', 'mirrored purple', 'shiny aqua'],
['dotted lavender', 'contain', 'light green', 'light magenta'],
['bright gold', 'contain', 'dim blue', 'dark salmon', 'posh crimson'],
['striped violet', 'contain', 'posh plum', 'drab crimson', 'faded orange', 'dotted green'],
['dull plum', 'contain', 'dark maroon'],
['striped tomato', 'contain', 'striped maroon', 'plaid turquoise'],
['muted bronze', 'contain', 'plaid red'],
['dull lavender', 'contain', 'plaid white'],
['dark bronze', 'contain', 'clear turquoise', 'dim purple', 'bright turquoise', 'striped coral'],
['muted green', 'contain', 'plaid white', 'pale blue', 'plaid tan', 'clear turquoise'],
['mirrored bronze', 'contain', 'faded white', 'bright teal', 'clear red', 'clear crimson'],
['clear silver', 'contain', 'dim yellow', 'striped brown', 'muted magenta'],
['dark indigo', 'contain', 'faded maroon', 'mirrored purple'],
['posh silver', 'contain', 'dotted maroon', 'striped indigo', 'faded red'],
['light teal', 'contain', 'vibrant beige', 'striped plum', 'dim salmon'],
['dull orange', 'contain', 'shiny teal', 'muted teal', 'dark fuchsia', 'bright magenta'],
['muted red', 'contain', 'mirrored magenta'],
['dotted gray', 'contain', 'dull maroon', 'mirrored blue', 'mirrored red'],
['light lime', 'contain', 'plaid fuchsia', 'posh plum'],
['pale coral', 'contain', 'shiny gray', 'plaid beige'],
['dim brown', 'contain', 'faded gray'],
['drab tan', 'contain', 'dotted crimson'],
['clear chartreuse', 'contain', 'faded maroon', 'plaid white'],
['posh maroon', 'contain', 'clear beige', 'light black'],
['mirrored blue', 'contain', 'faded gray', 'mirrored olive', 'pale lime'],
['clear coral', 'contain', 'plaid fuchsia', 'drab yellow', 'light bronze'],
['mirrored orange', 'contain', 'mirrored lavender', 'faded orange', 'mirrored gold', 'dim silver'],
['pale bronze', 'contain', 'plaid orange', 'wavy chartreuse', 'clear red'],
['faded yellow', 'contain', 'posh green'],
['light magenta', 'contain', 'clear silver', 'pale magenta'],
['clear aqua', 'contain', 'dark tan'],
['clear yellow', 'contain', 'dim violet', 'drab bronze'],
['plaid yellow', 'contain', 'dotted salmon'],
['pale salmon', 'contain', 'plaid olive', 'clear beige'],
['bright magenta', 'contain', 'shiny maroon', 'bright maroon', 'shiny white'],
['dull brown', 'contain', 'posh fuchsia', 'dotted tan'],
['muted magenta', 'contain', 'no other'],
['muted lavender', 'contain', 'light aqua', 'faded maroon', 'plaid lavender'],
['dotted violet', 'contain', 'pale red', 'mirrored magenta'],
['wavy gray', 'contain', 'dark indigo', 'dim yellow', 'posh lime', 'wavy yellow'],
['posh beige', 'contain', 'mirrored magenta', 'striped brown', 'mirrored aqua', 'dotted silver'],
['drab crimson', 'contain', 'faded coral', 'light indigo', 'dark indigo'],
['wavy magenta', 'contain', 'clear gold', 'dim purple', 'pale green'],
['dim fuchsia', 'contain', 'drab teal', 'plaid brown', 'faded orange'],
['faded indigo', 'contain', 'faded orange', 'striped turquoise', 'pale salmon', 'bright cyan'],
['posh yellow', 'contain', 'pale gold', 'posh coral', 'dotted tan'],
['muted chartreuse', 'contain', 'plaid brown', 'dull green'],
['dotted plum', 'contain', 'mirrored purple', 'drab tan', 'striped white'],
['clear plum', 'contain', 'posh green'],
['striped red', 'contain', 'striped tomato', 'wavy fuchsia', 'clear yellow'],
['striped aqua', 'contain', 'posh teal', 'bright beige'],
['dim gold', 'contain', 'dull salmon', 'mirrored red', 'mirrored black'],
['mirrored brown', 'contain', 'mirrored salmon'],
['wavy plum', 'contain', 'shiny yellow', 'light crimson', 'dotted silver'],
['striped coral', 'contain', 'no other'],
['dark gray', 'contain', 'dotted salmon', 'clear brown', 'posh crimson', 'mirrored plum'],
['posh chartreuse', 'contain', 'wavy fuchsia', 'mirrored beige'],
['dotted gold', 'contain', 'dark lavender', 'striped black'],
['posh green', 'contain', 'dotted salmon', 'pale salmon', 'posh red', 'dim green'],
['plaid blue', 'contain', 'posh green', 'dim cyan', 'dull bronze'],
['light lavender', 'contain', 'muted green', 'light violet', 'muted plum'],
['pale plum', 'contain', 'muted lavender', 'light bronze', 'plaid crimson'],
['mirrored indigo', 'contain', 'dark violet', 'wavy purple', 'plaid tan'],
['dim violet', 'contain', 'mirrored black', 'dull lime', 'posh crimson', 'pale brown'],
['shiny coral', 'contain', 'light aqua', 'plaid olive', 'bright turquoise'],
['dotted cyan', 'contain', 'shiny olive', 'light bronze', 'dim plum'],
['mirrored teal', 'contain', 'dim violet'],
['shiny purple', 'contain', 'dim magenta', 'clear white', 'posh silver', 'shiny turquoise'],
['shiny gray', 'contain', 'pale lavender', 'vibrant turquoise', 'faded maroon', 'bright cyan'],
['mirrored chartreuse', 'contain', 'clear white'],
['light beige', 'contain', 'mirrored turquoise', 'plaid maroon', 'light silver'],
['dull tomato', 'contain', 'shiny gold', 'pale blue'],
['plaid teal', 'contain', 'dim purple', 'striped turquoise', 'light indigo', 'faded red'],
['vibrant aqua', 'contain', 'mirrored turquoise', 'light plum', 'clear teal', 'dull blue'],
['dotted turquoise', 'contain', 'bright fuchsia', 'dim blue', 'posh green', 'wavy red'],
['dark lavender', 'contain', 'mirrored lime', 'plaid red', 'striped white', 'plaid tomato'],
['plaid tan', 'contain', 'plaid white'],
['pale olive', 'contain', 'clear salmon'],
['wavy indigo', 'contain', 'plaid black', 'wavy teal', 'mirrored salmon'],
['drab chartreuse', 'contain', 'light lime', 'drab yellow'],
['drab blue', 'contain', 'vibrant brown'],
['muted purple', 'contain', 'shiny yellow'],
['muted aqua', 'contain', 'striped white'],
['mirrored violet', 'contain', 'wavy violet', 'mirrored aqua'],
['bright cyan', 'contain', 'wavy fuchsia', 'dark coral', 'shiny orange'],
['posh teal', 'contain', 'bright gray', 'faded gray', 'plaid turquoise'],
['muted lime', 'contain', 'striped coral', 'dark tan', 'plaid cyan'],
['mirrored crimson', 'contain', 'faded violet', 'posh purple'],
['light blue', 'contain', 'dotted blue', 'dark gold', 'bright cyan', 'light crimson'],
['dull beige', 'contain', 'dark turquoise', 'mirrored violet', 'muted crimson'],
['dark cyan', 'contain', 'muted blue'],
['dim turquoise', 'contain', 'shiny silver', 'pale yellow', 'plaid chartreuse', 'posh bronze'],
['faded brown', 'contain', 'dim silver', 'mirrored bronze'],
['wavy bronze', 'contain', 'shiny tomato', 'dim salmon'],
['pale brown', 'contain', 'pale tan', 'plaid olive', 'posh lavender', 'shiny aqua'],
['dull white', 'contain', 'dull red', 'dark gold', 'striped magenta', 'muted green'],
['plaid crimson', 'contain', 'drab bronze', 'pale blue'],
['bright lavender', 'contain', 'dark bronze'],
['plaid red', 'contain', 'striped turquoise', 'dull crimson', 'striped brown', 'clear crimson'],
['muted gold', 'contain', 'dotted black', 'striped salmon', 'drab purple', 'bright red'],
['striped silver', 'contain', 'posh black'],
['bright aqua', 'contain', 'light orange', 'wavy blue', 'dull lime'],
['plaid fuchsia', 'contain', 'shiny orange'],
['bright violet', 'contain', 'drab turquoise', 'dim cyan', 'pale blue', 'wavy blue'],
['dim white', 'contain', 'plaid black', 'plaid violet', 'light gray'],
['bright tan', 'contain', 'bright gold', 'shiny salmon', 'muted magenta', 'dotted black'],
['shiny bronze', 'contain', 'light aqua', 'clear crimson', 'light beige', 'clear blue'],
['muted silver', 'contain', 'striped lavender'],
['dull red', 'contain', 'dim coral', 'faded plum', 'plaid red'],
['wavy aqua', 'contain', 'dotted fuchsia', 'mirrored tomato'],
['dark olive', 'contain', 'muted yellow', 'shiny gold', 'posh crimson'],
['dark crimson', 'contain', 'shiny aqua', 'wavy black'],
['dark brown', 'contain', 'drab lavender', 'posh green', 'pale turquoise'],
['pale blue', 'contain', 'striped coral', 'shiny gold'],
['vibrant blue', 'contain', 'mirrored lavender', 'dark aqua', 'wavy coral'],
['posh cyan', 'contain', 'dull lavender', 'striped gray', 'vibrant orange'],
['faded red', 'contain', 'posh crimson', 'wavy coral', 'clear beige', 'dotted silver'],
['vibrant gold', 'contain', 'drab lavender', 'dim magenta', 'bright tomato', 'light magenta'],
['shiny chartreuse', 'contain', 'vibrant turquoise'],
['clear gray', 'contain', 'wavy coral', 'dark salmon', 'dark indigo'],
['pale maroon', 'contain', 'posh tomato', 'bright tan'],
['light turquoise', 'contain', 'drab fuchsia', 'bright silver', 'light green'],
['muted crimson', 'contain', 'dim yellow', 'wavy fuchsia', 'mirrored magenta', 'clear beige'],
['dull gray', 'contain', 'posh green'],
['light fuchsia', 'contain', 'dark gold', 'plaid black', 'bright lavender'],
['striped green', 'contain', 'striped fuchsia', 'dull tomato', 'posh crimson'],
['mirrored purple', 'contain', 'posh crimson', 'mirrored magenta', 'wavy violet', 'striped coral'],
['vibrant black', 'contain', 'clear magenta', 'muted salmon', 'posh blue'],
['plaid beige', 'contain', 'dark black', 'plaid yellow', 'bright violet'],
['pale teal', 'contain', 'pale crimson'],
['striped turquoise', 'contain', 'no other'],
['dim purple', 'contain', 'dull crimson', 'bright red'],
['faded cyan', 'contain', 'posh aqua', 'dull green', 'dark olive'],
['mirrored cyan', 'contain', 'plaid salmon', 'dim salmon', 'posh tomato'],
['striped purple', 'contain', 'faded salmon', 'bright tan', 'drab white'],
['bright blue', 'contain', 'light purple', 'pale yellow'],
['faded bronze', 'contain', 'light indigo', 'plaid green', 'posh orange'],
['striped white', 'contain', 'drab indigo', 'wavy tomato', 'dotted fuchsia', 'dim silver'],
['clear lime', 'contain', 'dotted magenta', 'striped magenta', 'bright coral', 'mirrored silver'],
['bright white', 'contain', 'dim lavender'],
['dim crimson', 'contain', 'posh black', 'mirrored silver'],
['clear olive', 'contain', 'vibrant purple', 'drab lavender', 'pale violet'],
['light coral', 'contain', 'dotted green', 'wavy aqua', 'dark salmon', 'light gold'],
['muted plum', 'contain', 'plaid tan', 'mirrored silver', 'vibrant turquoise'],
['dim plum', 'contain', 'bright plum'],
['drab bronze', 'contain', 'light indigo', 'striped brown', 'clear gold', 'clear gray'],
['plaid maroon', 'contain', 'dotted orange', 'light magenta', 'faded salmon', 'pale yellow'],
['wavy violet', 'contain', 'dotted silver', 'dull crimson', 'mirrored aqua', 'striped brown'],
['pale crimson', 'contain', 'bright chartreuse', 'light turquoise', 'bright gray', 'muted bronze'],
['mirrored aqua', 'contain', 'no other'],
['clear crimson', 'contain', 'pale salmon', 'mirrored magenta', 'striped coral', 'plaid olive'],
['dark tan', 'contain', 'wavy silver', 'dark aqua'],
['wavy maroon', 'contain', 'clear gray'],
['light crimson', 'contain', 'clear silver'],
['vibrant green', 'contain', 'clear magenta', 'dim white', 'plaid black'],
['bright bronze', 'contain', 'light brown'],
['light maroon', 'contain', 'bright red', 'bright tan', 'dim silver', 'pale salmon'],
['dark coral', 'contain', 'light crimson'],
['pale silver', 'contain', 'mirrored magenta', 'posh red', 'muted yellow', 'dark salmon'],
['dotted crimson', 'contain', 'faded salmon', 'vibrant beige', 'dim beige'],
['dull silver', 'contain', 'striped brown', 'shiny magenta'],
['striped beige', 'contain', 'clear crimson'],
['faded orange', 'contain', 'drab white', 'striped salmon', 'bright chartreuse'],
['drab olive', 'contain', 'clear purple'],
['dull maroon', 'contain', 'dotted magenta'],
['vibrant lavender', 'contain', 'light tomato', 'shiny teal'],
['dotted chartreuse', 'contain', 'faded white', 'light brown'],
['drab cyan', 'contain', 'pale coral', 'light purple', 'drab bronze', 'dim beige'],
['bright teal', 'contain', 'vibrant plum', 'dull tan', 'dim tomato', 'dark violet'],
['wavy fuchsia', 'contain', 'dim green', 'wavy violet'],
['drab black', 'contain', 'striped tomato', 'light salmon', 'dim yellow', 'shiny black'],
['dark green', 'contain', 'dark tan'],
['clear tomato', 'contain', 'mirrored gold', 'dark gold'],
['plaid aqua', 'contain', 'dotted coral', 'muted white'],
['plaid white', 'contain', 'clear crimson', 'wavy gold', 'pale lime', 'striped brown'],
['muted black', 'contain', 'wavy tan', 'mirrored turquoise'],
['faded aqua', 'contain', 'dull turquoise', 'vibrant tan'],
['vibrant brown', 'contain', 'pale silver', 'drab orange', 'clear olive'],
['pale cyan', 'contain', 'faded cyan', 'mirrored tan', 'vibrant aqua', 'light gold'],
['shiny salmon', 'contain', 'posh red', 'light chartreuse', 'striped brown'],
['plaid lime', 'contain', 'dim gold', 'clear magenta'],
['drab tomato', 'contain', 'clear orange'],
['faded beige', 'contain', 'dark crimson', 'mirrored tan'],
['vibrant crimson', 'contain', 'wavy blue', 'clear gray'],
['dotted maroon', 'contain', 'dotted red', 'wavy silver', 'drab brown', 'dark black'],
['striped indigo', 'contain', 'striped orange'],
['dim orange', 'contain', 'wavy lavender', 'drab brown', 'dull salmon'],
['posh olive', 'contain', 'faded indigo', 'plaid white'],
['striped lavender', 'contain', 'bright red'],
['muted violet', 'contain', 'bright tan', 'striped coral', 'drab bronze'],
['wavy tan', 'contain', 'striped brown', 'dim salmon', 'posh fuchsia', 'mirrored violet'],
['dull magenta', 'contain', 'clear red', 'dull green', 'posh lime', 'mirrored gold'],
['dotted red', 'contain', 'mirrored black', 'dull bronze', 'dim salmon'],
['drab turquoise', 'contain', 'muted yellow', 'light indigo', 'dotted black'],
['faded purple', 'contain', 'dim orange', 'dark red'],
['faded teal', 'contain', 'bright fuchsia'],
['plaid gray', 'contain', 'pale aqua'],
['bright black', 'contain', 'wavy violet'],
['dim green', 'contain', 'mirrored aqua', 'light chartreuse', 'light indigo'],
['dark gold', 'contain', 'mirrored red', 'bright lavender', 'pale crimson'],
['dark plum', 'contain', 'pale salmon'],
['wavy orange', 'contain', 'light tan', 'pale yellow', 'shiny aqua', 'vibrant orange'],
['bright chartreuse', 'contain', 'dark salmon', 'plaid olive'],
['wavy purple', 'contain', 'faded coral', 'vibrant orange'],
['shiny violet', 'contain', 'plaid chartreuse', 'plaid brown'],
['posh indigo', 'contain', 'posh salmon'],
['clear indigo', 'contain', 'light violet'],
['plaid purple', 'contain', 'clear blue', 'muted gold', 'dull brown'],
['posh lavender', 'contain', 'plaid black', 'shiny orange', 'posh red', 'plaid cyan'],
['wavy silver', 'contain', 'plaid cyan', 'plaid olive'],
['posh salmon', 'contain', 'clear gray', 'dotted silver', 'shiny aqua'],
['faded lavender', 'contain', 'drab chartreuse', 'plaid magenta', 'vibrant tomato'],
['pale red', 'contain', 'bright red', 'pale lime', 'striped turquoise'],
['bright purple', 'contain', 'muted lavender'],
['dim magenta', 'contain', 'plaid teal', 'posh lavender'],
['posh magenta', 'contain', 'pale teal', 'mirrored tomato', 'striped gold', 'bright tomato'],
['bright brown', 'contain', 'dark fuchsia', 'pale yellow', 'shiny crimson'],
['light red', 'contain', 'wavy teal'],
['pale turquoise', 'contain', 'mirrored yellow'],
['vibrant magenta', 'contain', 'dark gold'],
['dotted salmon', 'contain', 'wavy violet', 'shiny aqua', 'dull bronze'],
['mirrored gray', 'contain', 'dark plum', 'striped gray', 'plaid violet'],
['dim yellow', 'contain', 'striped turquoise', 'pale salmon', 'mirrored magenta', 'striped brown'],
['drab lavender', 'contain', 'faded maroon', 'shiny orange'],
['muted maroon', 'contain', 'wavy tomato', 'drab red'],
['clear gold', 'contain', 'mirrored olive', 'striped turquoise'],
['light bronze', 'contain', 'muted lavender'],
['dotted bronze', 'contain', 'dotted turquoise'],
['pale tomato', 'contain', 'shiny beige', 'mirrored tomato', 'dotted maroon', 'wavy teal'],
['pale chartreuse', 'contain', 'plaid silver'],
['drab magenta', 'contain', 'wavy tomato', 'drab brown', 'posh maroon', 'mirrored teal'],
['posh blue', 'contain', 'muted lime', 'mirrored tomato', 'shiny aqua'],
['posh purple', 'contain', 'dull maroon'],
['posh bronze', 'contain', 'mirrored orange', 'pale violet', 'plaid gray'],
['pale gold', 'contain', 'striped brown', 'muted green'],
['faded crimson', 'contain', 'drab salmon', 'posh crimson', 'light purple', 'clear red'],
['vibrant fuchsia', 'contain', 'posh beige', 'dotted indigo', 'pale silver', 'clear black'],
['faded lime', 'contain', 'posh plum', 'shiny aqua', 'dull chartreuse'],
['shiny fuchsia', 'contain', 'shiny salmon', 'pale chartreuse'],
['wavy lavender', 'contain', 'dark blue', 'muted salmon'],
['pale indigo', 'contain', 'wavy gold', 'clear silver', 'dim blue'],
['drab violet', 'contain', 'muted yellow'],
['shiny plum', 'contain', 'bright black', 'pale teal', 'light red', 'plaid magenta'],
['shiny gold', 'contain', 'vibrant chartreuse'],
['wavy gold', 'contain', 'posh beige', 'mirrored aqua'],
['dark salmon', 'contain', 'light aqua', 'posh red', 'mirrored black', 'posh crimson'],
['pale tan', 'contain', 'wavy coral'],
['dull tan', 'contain', 'bright cyan'],
['clear maroon', 'contain', 'dim magenta', 'shiny lavender'],
['light white', 'contain', 'dark brown', 'bright fuchsia'],
['wavy red', 'contain', 'dim red'],
['dotted aqua', 'contain', 'striped teal'],
['bright beige', 'contain', 'shiny tomato'],
['plaid indigo', 'contain', 'muted bronze'],
['light yellow', 'contain', 'striped black', 'muted gold', 'dotted tan', 'dark coral'],
['vibrant silver', 'contain', 'dim blue'],
['posh tomato', 'contain', 'bright red', 'posh red', 'plaid olive', 'clear crimson'],
['pale magenta', 'contain', 'mirrored blue', 'dull maroon', 'dark violet'],
['light indigo', 'contain', 'plaid olive', 'plaid black', 'dark indigo'],
['shiny green', 'contain', 'vibrant chartreuse', 'bright lavender', 'wavy crimson', 'dull red'],
['striped maroon', 'contain', 'posh coral', 'striped gray', 'clear plum'],
['posh fuchsia', 'contain', 'wavy gold', 'posh beige'],
['dim coral', 'contain', 'wavy gold', 'muted lavender'],
['faded maroon', 'contain', 'dim purple', 'bright red', 'wavy violet', 'mirrored aqua'],
['striped black', 'contain', 'plaid fuchsia', 'bright lavender', 'dull black'],
['mirrored gold', 'contain', 'dotted silver'],
['light tomato', 'contain', 'pale brown', 'wavy coral'],
['dark white', 'contain', 'mirrored tomato', 'striped orange', 'dim olive', 'dotted blue'],
['dotted green', 'contain', 'clear plum'],
['dotted brown', 'contain', 'clear magenta'],
['muted orange', 'contain', 'muted olive', 'faded yellow', 'faded turquoise', 'muted violet'],
['dull olive', 'contain', 'dotted teal'],
['mirrored lime', 'contain', 'dark violet', 'muted yellow'],
['wavy green', 'contain', 'bright lime'],
['drab purple', 'contain', 'striped turquoise', 'clear silver', 'muted lime'],
['clear cyan', 'contain', 'light lavender'],
['dim black', 'contain', 'dull black'],
['posh gray', 'contain', 'mirrored magenta'],
['dotted yellow', 'contain', 'light maroon', 'clear blue', 'dark maroon'],
['mirrored olive', 'contain', 'dark violet', 'dull crimson', 'dim salmon', 'bright tan'],
['dark blue', 'contain', 'dull aqua', 'dim teal'],
['dull bronze', 'contain', 'striped coral'],
['drab maroon', 'contain', 'dark bronze', 'wavy blue'],
['mirrored lavender', 'contain', 'clear black'],
['dim beige', 'contain', 'shiny silver', 'dark purple', 'dull green'],
['light violet', 'contain', 'muted gray', 'wavy tomato'],
['striped chartreuse', 'contain', 'dull tan', 'dim salmon'],
['posh red', 'contain', 'clear crimson', 'striped coral', 'bright red'],
['wavy beige', 'contain', 'muted silver', 'pale teal'],
['light gray', 'contain', 'drab indigo', 'posh crimson', 'dark tan', 'pale red'],
['muted white', 'contain', 'wavy fuchsia'],
['pale violet', 'contain', 'wavy tan', 'plaid yellow'],
['drab fuchsia', 'contain', 'plaid lavender', 'pale lime'],
['clear green', 'contain', 'light indigo'],
['vibrant turquoise', 'contain', 'vibrant tan', 'clear silver'],
['faded green', 'contain', 'striped orange', 'bright fuchsia'],
['striped tan', 'contain', 'wavy silver'],
['clear white', 'contain', 'vibrant fuchsia', 'pale silver', 'vibrant indigo', 'shiny silver'],
['dim cyan', 'contain', 'mirrored black', 'plaid chartreuse', 'bright gold'],
['muted gray', 'contain', 'mirrored violet', 'dim yellow'],
['mirrored maroon', 'contain', 'clear crimson', 'clear gray', 'dotted salmon'],
['dim bronze', 'contain', 'striped plum', 'bright orange'],
['shiny tomato', 'contain', 'dim yellow', 'faded bronze', 'drab maroon', 'dim gold'],
['muted olive', 'contain', 'mirrored yellow', 'bright olive'],
['shiny brown', 'contain', 'bright coral'],
['clear blue', 'contain', 'pale green', 'light violet', 'plaid crimson'],
['faded tan', 'contain', 'dim crimson', 'mirrored turquoise', 'drab gold'],
['muted cyan', 'contain', 'drab silver'],
['mirrored red', 'contain', 'bright gold'],
['faded salmon', 'contain', 'posh red', 'dull crimson', 'dotted salmon', 'shiny olive'],
['dark purple', 'contain', 'dim magenta'],
['dotted lime', 'contain', 'posh fuchsia', 'wavy tan', 'mirrored aqua', 'shiny aqua'],
['posh tan', 'contain', 'plaid tan', 'drab fuchsia'],
['dotted teal', 'contain', 'dull crimson', 'bright lavender', 'wavy tan', 'muted crimson'],
['clear purple', 'contain', 'shiny aqua', 'dim cyan', 'dotted black', 'dull gray'],
['light gold', 'contain', 'dotted magenta', 'dark olive', 'dim cyan', 'dark indigo'],
['mirrored silver', 'contain', 'plaid black', 'vibrant beige', 'mirrored purple', 'dotted lime'],
['posh black', 'contain', 'wavy violet', 'plaid teal'],
['faded silver', 'contain', 'vibrant purple', 'shiny olive'],
['drab teal', 'contain', 'dotted salmon', 'posh beige', 'mirrored tan', 'muted green'],
['dark maroon', 'contain', 'dark tan', 'mirrored gold', 'dim plum'],
['striped plum', 'contain', 'striped coral', 'clear brown', 'striped brown'],
['striped bronze', 'contain', 'drab yellow', 'striped chartreuse', 'posh plum', 'clear blue'],
['drab plum', 'contain', 'shiny gold', 'vibrant tan', 'light gold'],
['clear fuchsia', 'contain', 'vibrant red'],
['dark silver', 'contain', 'clear salmon', 'faded yellow', 'shiny lavender', 'wavy fuchsia'],
['striped lime', 'contain', 'dim tomato', 'light fuchsia', 'light lime'],
['wavy salmon', 'contain', 'shiny tomato', 'light tomato'],
['dim maroon', 'contain', 'faded beige', 'bright turquoise', 'dull purple', 'vibrant olive'],
['faded chartreuse', 'contain', 'mirrored blue', 'posh white', 'wavy magenta'],
['clear magenta', 'contain', 'muted bronze', 'dim yellow', 'dotted lime'],
['bright silver', 'contain', 'bright gold', 'wavy yellow'],
['dull violet', 'contain', 'faded beige', 'mirrored orange', 'mirrored aqua'],
['vibrant cyan', 'contain', 'clear aqua', 'dark maroon', 'pale tan'],
['light chartreuse', 'contain', 'wavy gold', 'posh tomato', 'clear silver'],
['dotted olive', 'contain', 'wavy crimson', 'drab tomato'],
['posh aqua', 'contain', 'striped brown'],
['posh orange', 'contain', 'wavy coral'],
['dull cyan', 'contain', 'dark tan', 'dull gray', 'drab turquoise', 'shiny aqua'],
['muted teal', 'contain', 'dull blue'],
['bright turquoise', 'contain', 'dull bronze', 'plaid lavender'],
['plaid tomato', 'contain', 'muted lime', 'light indigo', 'posh tomato'],
['dim salmon', 'contain', 'dark indigo', 'plaid brown', 'clear crimson', 'clear silver'],
['posh brown', 'contain', 'clear silver', 'faded cyan', 'posh crimson'],
['dark turquoise', 'contain', 'drab crimson', 'striped coral'],
['dull crimson', 'contain', 'no other'],
['striped teal', 'contain', 'plaid lavender', 'faded red'],
['dotted blue', 'contain', 'muted beige'],
['vibrant plum', 'contain', 'pale lime', 'posh red', 'dull bronze', 'drab silver'],
['wavy coral', 'contain', 'mirrored magenta', 'dim yellow', 'bright red', 'posh crimson'],
['dark chartreuse', 'contain', 'dotted fuchsia', 'mirrored silver', 'mirrored aqua', 'dim cyan'],
['vibrant teal', 'contain', 'vibrant silver'],
['shiny beige', 'contain', 'posh teal'],
['dim olive', 'contain', 'clear gray', 'wavy gold'],
['drab yellow', 'contain', 'light chartreuse', 'striped crimson', 'faded gray'],
['dull chartreuse', 'contain', 'light lavender'],
['dotted silver', 'contain', 'no other'],
['shiny blue', 'contain', 'dull brown', 'dark coral', 'shiny crimson'],
['mirrored black', 'contain', 'mirrored magenta', 'striped turquoise', 'plaid cyan'],
['dull black', 'contain', 'dim purple', 'dark salmon', 'mirrored gold'],
['mirrored beige', 'contain', 'striped fuchsia', 'plaid black', 'dim red', 'light green'],
['dim chartreuse', 'contain', 'shiny yellow'],
['shiny teal', 'contain', 'vibrant maroon'],
['dim tomato', 'contain', 'plaid tomato', 'mirrored violet', 'mirrored orange'],
['vibrant beige', 'contain', 'plaid black', 'dotted salmon', 'posh fuchsia'],
['dull aqua', 'contain', 'wavy tan', 'bright olive'],
['pale lime', 'contain', 'bright turquoise', 'dim yellow', 'shiny orange'],
['bright orange', 'contain', 'muted gold', 'clear white'],
['drab salmon', 'contain', 'dark fuchsia', 'dull gray'],
['mirrored salmon', 'contain', 'posh plum', 'dotted silver', 'clear plum', 'dull black'],
['shiny silver', 'contain', 'drab lavender', 'dim violet', 'dark aqua', 'vibrant chartreuse'],
['plaid coral', 'contain', 'dim blue', 'vibrant lime'],
['mirrored white', 'contain', 'pale gold', 'shiny green', 'striped white'],
['pale gray', 'contain', 'mirrored gold', 'wavy silver', 'posh green', 'mirrored red'],
['pale white', 'contain', 'shiny turquoise', 'bright plum', 'dotted bronze'],
['muted fuchsia', 'contain', 'plaid turquoise', 'dark aqua', 'pale brown', 'striped plum'],
['striped yellow', 'contain', 'posh red', 'plaid black'],
['plaid silver', 'contain', 'dark indigo', 'clear teal', 'dotted black'],
['plaid black', 'contain', 'dull crimson'],
['vibrant lime', 'contain', 'dotted fuchsia', 'dull bronze', 'dark aqua', 'dark salmon'],
['dotted white', 'contain', 'dim red'],
['light aqua', 'contain', 'mirrored aqua', 'striped brown', 'posh crimson'],
['striped brown', 'contain', 'dotted silver', 'clear beige'],
['vibrant red', 'contain', 'bright olive', 'plaid chartreuse', 'light olive', 'dim violet'],
['dim teal', 'contain', 'clear violet'],
['bright lime', 'contain', 'dull lavender', 'pale turquoise'],
['striped crimson', 'contain', 'bright gray', 'dark green', 'posh plum', 'shiny coral'],
['mirrored tomato', 'contain', 'wavy tan'],
['dull blue', 'contain', 'bright turquoise', 'striped brown'],
['mirrored yellow', 'contain', 'vibrant purple', 'faded bronze', 'dull lavender', 'light plum'],
['plaid gold', 'contain', 'striped olive', 'dotted chartreuse'],
['dotted coral', 'contain', 'bright teal'],
['wavy crimson', 'contain', 'dotted salmon', 'dull crimson'],
['dark aqua', 'contain', 'dull crimson', 'light aqua', 'mirrored purple', 'striped brown'],
['vibrant yellow', 'contain', 'faded beige', 'dark brown', 'wavy bronze'],
['wavy teal', 'contain', 'dotted magenta'],
['drab white', 'contain', 'pale blue'],
['muted salmon', 'contain', 'posh salmon', 'bright chartreuse'],
['light purple', 'contain', 'dark maroon'],
['faded black', 'contain', 'dull gold'],
['muted turquoise', 'contain', 'wavy silver', 'clear purple'],
['plaid chartreuse', 'contain', 'posh crimson', 'striped brown'],
['vibrant tan', 'contain', 'dull blue', 'posh black', 'faded red', 'plaid magenta'],
['shiny orange', 'contain', 'vibrant chartreuse', 'shiny gold'],
['shiny lavender', 'contain', 'posh teal'],
['pale black', 'contain', 'dark brown'],
['shiny cyan', 'contain', 'wavy tomato', 'bright bronze', 'faded crimson'],
['faded olive', 'contain', 'clear aqua'],
['dark violet', 'contain', 'faded red'],
['light orange', 'contain', 'posh aqua', 'light crimson', 'dark maroon'],
['drab silver', 'contain', 'pale blue'],
['plaid bronze', 'contain', 'mirrored orange', 'plaid cyan', 'dotted black'],
['plaid violet', 'contain', 'plaid fuchsia', 'clear teal'],
['clear turquoise', 'contain', 'dim yellow', 'plaid teal', 'plaid red', 'dotted salmon'],
['plaid lavender', 'contain', 'clear silver', 'dull bronze'],
['mirrored green', 'contain', 'striped lavender'],
['faded white', 'contain', 'light chartreuse'],
['bright crimson', 'contain', 'mirrored purple'],
['dotted beige', 'contain', 'pale salmon', 'dotted teal', 'light lavender', 'wavy violet'],
['pale green', 'contain', 'dark gold', 'clear gray'],
['dull indigo', 'contain', 'striped brown', 'plaid plum'],
['shiny yellow', 'contain', 'striped silver', 'mirrored plum', 'muted red', 'clear gold'],
['bright maroon', 'contain', 'muted crimson', 'plaid chartreuse', 'dim violet', 'plaid blue'],
['vibrant orange', 'contain', 'posh plum', 'shiny gold'],
['faded fuchsia', 'contain', 'dotted aqua'],
['bright indigo', 'contain', 'shiny coral', 'muted salmon', 'clear white', 'vibrant maroon'],
['shiny indigo', 'contain', 'dark red', 'pale lime'],
['light cyan', 'contain', 'clear black', 'mirrored aqua', 'faded beige', 'faded salmon'],
['faded gold', 'contain', 'muted lime', 'plaid fuchsia'],
['muted coral', 'contain', 'faded indigo', 'dim beige', 'dotted orange', 'posh black'],
['drab gray', 'contain', 'clear magenta', 'bright tomato', 'dull gold'],
['vibrant salmon', 'contain', 'bright gold'],
['dark red', 'contain', 'posh black', 'faded teal'],
['wavy blue', 'contain', 'dim green', 'dull green', 'posh aqua'],
['mirrored turquoise', 'contain', 'dull lime', 'dark gray', 'striped cyan', 'muted gold'],
['wavy chartreuse', 'contain', 'pale brown', 'shiny chartreuse', 'wavy fuchsia'],
['dim red', 'contain', 'bright blue', 'clear purple', 'wavy crimson', 'shiny black'],
['dull gold', 'contain', 'wavy blue'],
['faded blue', 'contain', 'plaid turquoise', 'vibrant indigo'],
['shiny aqua', 'contain', 'plaid cyan', 'posh crimson'],
['bright salmon', 'contain', 'posh red', 'shiny orange', 'vibrant crimson'],
['pale yellow', 'contain', 'plaid cyan'],
['plaid magenta', 'contain', 'plaid brown', 'pale yellow', 'drab fuchsia', 'clear black'],
['vibrant maroon', 'contain', 'dull tomato', 'dotted indigo', 'plaid teal', 'shiny gold'],
['drab orange', 'contain', 'wavy coral'],
['pale aqua', 'contain', 'wavy lime', 'drab turquoise'],
['shiny crimson', 'contain', 'posh black', 'drab fuchsia', 'plaid fuchsia', 'posh plum'],
['pale purple', 'contain', 'clear green', 'striped crimson', 'drab indigo'],
['faded magenta', 'contain', 'light red'],
['shiny tan', 'contain', 'plaid silver', 'light lavender', 'wavy purple'],
['vibrant indigo', 'contain', 'plaid beige'],
['wavy turquoise', 'contain', 'dark teal', 'dark cyan', 'mirrored olive', 'bright red'],
['striped blue', 'contain', 'vibrant lime', 'vibrant indigo', 'pale maroon', 'dark white'],
['faded tomato', 'contain', 'plaid tan', 'pale tan', 'wavy violet', 'pale lime'],
['bright green', 'contain', 'bright purple', 'posh magenta'],
['dark beige', 'contain', 'light green', 'light magenta', 'dotted lime', 'plaid salmon'],
['plaid green', 'contain', 'pale salmon'],
['bright red', 'contain', 'dotted silver'],
['drab lime', 'contain', 'dotted bronze'],
['muted indigo', 'contain', 'posh gray', 'dark lavender', 'plaid chartreuse', 'pale red'],
['muted tan', 'contain', 'muted brown', 'dull maroon'],
['plaid turquoise', 'contain', 'clear teal', 'dull tomato', 'dotted purple', 'posh salmon'],
['drab aqua', 'contain', 'bright lime', 'posh red']]

print(len(bags_list))

def find_gold(array, color):
  new_array = []
  for x in array:
    for y in x:
      if color in y:
        new_array.append(x)
  return new_array

# print(find_gold(bags_list, 'shiny gold'))  
# print('////////////////')


def get_bags(array, color):
  new_array = []
  for x in array:
    if x[0] != color:
      new_array.append(x[0])
  return new_array

can_take_gold_bags = get_bags(find_gold(bags_list, 'shiny gold'), 'shiny gold')
# print(can_take_gold_bags)
# print('////////////////')

import itertools

def get_next(array, colors):
  new_array = []
  for x in colors:
    new_array.append(get_bags(find_gold(array, x), x))
  new_array = itertools.chain(*new_array)
  return list(new_array)


def count_all(array):
  bags = get_bags(find_gold(bags_list, 'shiny gold'), 'shiny gold')
  total_count = len(bags)
  print(bags)
  print(len(bags))
  while len(bags) != 0:
    
    bags = get_next(array, bags)
    total_count = total_count + len(bags)
    print(['count', total_count])
    print(len(bags))
  return total_count

print(count_all(bags_list))

